### ISSUE TITLE
Checkboxes and Radio Buttons invisible

### ISSUE THREAD

**Issue by frhun** [B00merang-Project/Haiku#2]
In the GTK Widget Factory screenshot you can see that the Checkboxes and Radiobuttons are not visible.
![GTK Widget Factory](https://user-images.githubusercontent.com/28605587/124989609-94dcec80-e03f-11eb-8baf-20cf22845206.png)

**Comment by Elbullazul** [comment]
what distro and desktop are you using?

**Comment by frhun** [comment]
I was using Gnome ArchLinux, and it seems to have been one of the rare cases where there was an upstream bug. It works fine now.
